stages:
  - lint
  - test

lint:
  image: golangci/golangci-lint:v1.51-alpine
  stage: lint
  script:
    - go generate ./...
    - golangci-lint version
    - golangci-lint run --disable-all --enable=vet --enable=golint ./...

staticcheck:
  image: golang:1.20-alpine 
  stage: lint
  before_script:
    - go install honnef.co/go/tools/cmd/staticcheck@v0.4.2
  script:
    - staticcheck ./...

test:
  image: golang:1.20-alpine
  stage: test
  coverage: /\(statements\)(?:\s+)?(\d+(?:\.\d+)?%)/
  script:
    - CGO_ENABLED=0 go test ./... -coverprofile=coverage.out
    - go tool cover -html=coverage.out -o coverage.html
    - go tool cover -func coverage.out
  artifacts:
    expire_in: "3 days"
    paths:
      - coverage.html
